const C=window.TRANSFERONE_CONFIG||{};let service='Transfer';
const I={
EN:{hero:'ONE JOURNEY.<br><span>ONE STANDARD.</span>',lead:'Premium airport transfers, private chauffeur service and custom journeys across Moldova.',book:'BOOK A TRANSFER',quote:'GET A QUOTE →',pickup:'Pickup location',dropoff:'Drop-off location',date:'Date',time:'Time',passengers:'Passengers',vehicle:'Vehicle class',flight:'Flight number',luggage:'Luggage',contact:'Your phone / WhatsApp',notes:'Notes',services:'More than a ride.',fleet:'The right vehicle for every journey.',routes:'Popular routes',faq:'Before your ride.',standard:'STANDARD SEDAN',business:'BUSINESS CLASS',van:'VAN CLASS'},
RO:{hero:'O CĂLĂTORIE.<br><span>UN SINGUR STANDARD.</span>',lead:'Transferuri premium de la aeroport, șofer privat și călătorii personalizate în Moldova.',book:'REZERVĂ TRANSFER',quote:'CERE OFERTĂ →',pickup:'Loc preluare',dropoff:'Destinație',date:'Data',time:'Ora',passengers:'Pasageri',vehicle:'Clasa auto',flight:'Număr zbor',luggage:'Bagaje',contact:'Telefon / WhatsApp',notes:'Detalii',services:'Mai mult decât un drum.',fleet:'Mașina potrivită pentru fiecare călătorie.',routes:'Rute populare',faq:'Înainte de călătorie.',standard:'SEDAN STANDARD',business:'CLASA BUSINESS',van:'CLASA VAN'},
RU:{hero:'ОДНА ПОЕЗДКА.<br><span>ОДИН СТАНДАРТ.</span>',lead:'Премиальные трансферы из аэропорта, личный водитель и индивидуальные поездки по Молдове.',book:'ЗАКАЗАТЬ ТРАНСФЕР',quote:'ПОЛУЧИТЬ РАСЧЁТ →',pickup:'Откуда',dropoff:'Куда',date:'Дата',time:'Время',passengers:'Пассажиры',vehicle:'Класс автомобиля',flight:'Номер рейса',luggage:'Багаж',contact:'Телефон / WhatsApp',notes:'Комментарий',services:'Больше, чем просто поездка.',fleet:'Подходящий автомобиль для каждой поездки.',routes:'Популярные маршруты',faq:'Перед поездкой.',standard:'STANDARD SEDAN',business:'BUSINESS CLASS',van:'VAN CLASS'},
IT:{hero:'UN VIAGGIO.<br><span>UN SOLO STANDARD.</span>',lead:'Transfer aeroportuali premium, autista privato e viaggi su misura in tutta la Moldavia.',book:'PRENOTA TRANSFER',quote:'RICHIEDI PREVENTIVO →',pickup:'Partenza',dropoff:'Destinazione',date:'Data',time:'Ora',passengers:'Passeggeri',vehicle:'Classe veicolo',flight:'Numero volo',luggage:'Bagagli',contact:'Telefono / WhatsApp',notes:'Note',services:'Più di un semplice viaggio.',fleet:'Il veicolo giusto per ogni viaggio.',routes:'Tratte popolari',faq:'Prima del viaggio.',standard:'BERLINA STANDARD',business:'CLASSE BUSINESS',van:'CLASSE VAN'}};
function setLang(l){let d={...I.EN,...(I[l]||{})};document.documentElement.lang=l.toLowerCase();document.querySelectorAll('[data-t]').forEach(e=>{if(d[e.dataset.t]!=null)e.innerHTML=d[e.dataset.t]});localStorage.setItem('t1lang',l)}
function configLinks(){document.querySelectorAll('[data-phone]').forEach(e=>{e.textContent=C.phone||'Phone on confirmation';if(C.phone)e.href='tel:'+C.phone.replace(/\s/g,'')});document.querySelectorAll('[data-email]').forEach(e=>{e.textContent=C.email||'Booking email on confirmation';if(C.email)e.href='mailto:'+C.email})}
function submitBooking(){let ids=['pickup','dropoff','date','time','pax','vehicleClass','contact'];let vals={};let missing=[];ids.forEach(id=>{let e=document.getElementById(id);vals[id]=e?.value?.trim()||'';if(!vals[id])missing.push(e)});let st=document.getElementById('formStatus');if(missing.length){missing[0].focus();st.textContent='Please complete the required booking fields.';st.className='status show error';return}vals.flight=document.getElementById('flight').value.trim();vals.luggage=document.getElementById('luggage').value;vals.notes=document.getElementById('notes').value.trim();let msg=`TransferOne booking request\n\nService: ${service}\nPickup: ${vals.pickup}\nDrop-off: ${vals.dropoff}\nDate: ${vals.date}\nTime: ${vals.time}\nPassengers: ${vals.pax}\nVehicle: ${vals.vehicleClass}\nFlight: ${vals.flight||'-'}\nLuggage: ${vals.luggage||'-'}\nClient contact: ${vals.contact}\nNotes: ${vals.notes||'-'}`;if(C.whatsapp){window.open(`https://wa.me/${C.whatsapp}?text=${encodeURIComponent(msg)}`,'_blank');st.textContent='Opening WhatsApp with your booking details…';st.className='status show';return}if(C.email){location.href=`mailto:${C.email}?subject=${encodeURIComponent('TransferOne booking request')}&body=${encodeURIComponent(msg)}`;return}navigator.clipboard?.writeText(msg);st.textContent='Booking request prepared. Add the confirmed WhatsApp number or email in config.js before publishing.';st.className='status show'}
function chooseVehicle(v){document.getElementById('vehicleClass').value=v;document.getElementById('book').scrollIntoView({behavior:'smooth'})}
document.addEventListener('DOMContentLoaded',()=>{let l=localStorage.getItem('t1lang')||C.defaultLanguage||'EN',sel=document.getElementById('language');sel.value=l;setLang(l);sel.onchange=e=>setLang(e.target.value);configLinks();document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');service=t.dataset.mode});document.querySelectorAll('.faqQ').forEach(q=>q.onclick=()=>q.parentElement.classList.toggle('open'));let menu=document.getElementById('mobileMenu');document.getElementById('menuBtn').onclick=()=>menu.classList.toggle('open');menu.querySelectorAll('a').forEach(a=>a.onclick=()=>menu.classList.remove('open'));addEventListener('scroll',()=>document.querySelector('.nav').classList.toggle('scrolled',scrollY>20));let io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('show')),{threshold:.08});document.querySelectorAll('.fade').forEach(x=>io.observe(x));let today=new Date().toISOString().split('T')[0];document.getElementById('date').min=today});

// Hero video autoplay recovery
window.addEventListener('DOMContentLoaded',()=>{const v=document.querySelector('.heroVideo');if(!v)return;v.muted=true;v.playsInline=true;const play=()=>v.play().catch(()=>{});play();document.addEventListener('visibilitychange',()=>{if(!document.hidden)play()});window.addEventListener('pageshow',play);});
